services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=videos
      - VIDEO_SERVICE_API=http://videos:4000
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

networks:
  app-network:
    external: true