services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/usersdb
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules     # Prevent node_modules override from host
    command: ["npm", "run", "dev"]
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: