services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/videosdb
      - PORT=4000
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=videos
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - database
      - minio
    networks:
      - app-network

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: videosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - video_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - app-network

volumes:
  video_pgdata:
  minio_data:

networks:
  app-network: