name: auth

on:
  push:
    branches: [main]
    paths:
      - apps/auth/**
      - .github/workflows/auth.yml
      - .github/workflows/test.reusable.yml
  pull_request:
    paths:
      - apps/auth/**
      - .github/workflows/auth.yml
      - .github/workflows/test.reusable.yml

jobs:
  tests:
    uses: ./.github/workflows/test.reusable.yml
    with:
      service-path: apps/auth
    secrets: inherit