name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  NODE_VERSION: '22'
  TF_VERSION: '1.12.2'
  AWS_REGION: 'us-east-1'
  PORT: '3000'

jobs:
  # Test and Lint all applications
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [video, worker, auth]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client - ${{ matrix.app }}
      run: |
        # Check if the app has a prisma:generate script in package.json
        if grep -q '"prisma:generate"' apps/${{ matrix.app }}/package.json 2>/dev/null; then
          echo "Running Prisma generate for ${{ matrix.app }}"
          npm run prisma:generate --workspace=apps/${{ matrix.app }}
        else
          echo "Skipping Prisma generate for ${{ matrix.app }} (no Prisma setup found)"
        fi

    - name: Type check - ${{ matrix.app }}
      run: npm run typecheck --workspace=apps/${{ matrix.app }}

    - name: Lint - ${{ matrix.app }}
      run: npm run lint:check --workspace=apps/${{ matrix.app }}

    - name: Format check - ${{ matrix.app }}
      run: npm run format:check --workspace=apps/${{ matrix.app }}

    - name: Test - ${{ matrix.app }}
      run: npm run test --workspace=apps/${{ matrix.app }}

    - name: Generate Coverage Report - ${{ matrix.app }}
      if: github.event_name == 'pull_request'
      run: |
        # Create coverage directory if it doesn't exist
        mkdir -p coverage-reports
        
        # Run tests and capture coverage output
        npm run test --workspace=apps/${{ matrix.app }} > "coverage-reports/${{ matrix.app }}-coverage.txt" 2>&1 || true

    - name: Upload Coverage Artifacts - ${{ matrix.app }}
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.app }}
        path: coverage-reports/${{ matrix.app }}-coverage.txt
        retention-days: 1

  # Post Coverage Summary (on PR)
  coverage-summary:
    name: Coverage Summary
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Coverage Artifacts
      uses: actions/download-artifact@v4
      with:
        path: coverage-reports

    - name: Generate Coverage Summary
      run: |
        echo "## 🧪 Test Coverage Summary" > coverage-summary.md
        echo "" >> coverage-summary.md
        
        # Process each app's coverage
        for app in video worker auth; do
          if [ -f "coverage-reports/coverage-$app/$app-coverage.txt" ]; then
            # Extract overall coverage percentage
            COVERAGE=$(grep "All files" "coverage-reports/coverage-$app/$app-coverage.txt" | grep -o '[0-9]\+\.[0-9]\+' | head -1 || echo "0")
            
            # Determine emoji based on coverage percentage (using awk for comparison)
            EMOJI=$(awk -v cov="$COVERAGE" 'BEGIN {
              if (cov >= 90) print "🟢"
              else if (cov >= 80) print "🟡" 
              else print "🔴"
            }')
            
            echo "- **$app**: $EMOJI **${COVERAGE}%**" >> coverage-summary.md
          else
            echo "- **$app**: ❓ *No coverage data*" >> coverage-summary.md
          fi
        done
        
        echo "" >> coverage-summary.md
        echo "<details><summary>📊 Detailed Coverage Report</summary>" >> coverage-summary.md
        echo "" >> coverage-summary.md
        
        # Add detailed coverage for each app
        for app in video worker auth; do
          if [ -f "coverage-reports/coverage-$app/$app-coverage.txt" ]; then
            echo "### $app Service" >> coverage-summary.md
            echo "" >> coverage-summary.md
            echo '```' >> coverage-summary.md
            
            # Extract the coverage table
            sed -n '/% Coverage report/,/^$/p' "coverage-reports/coverage-$app/$app-coverage.txt" | head -30 >> coverage-summary.md
            
            echo '```' >> coverage-summary.md
            echo "" >> coverage-summary.md
          fi
        done
        
        echo "</details>" >> coverage-summary.md
        echo "" >> coverage-summary.md
        echo "*Generated by CI Pipeline* 🤖" >> coverage-summary.md
        echo "" >> coverage-summary.md
        echo "<!-- CI-COVERAGE-SUMMARY -->" >> coverage-summary.md

    - name: Post Coverage Comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const coverageSummary = fs.readFileSync('coverage-summary.md', 'utf8');
          
          try {
            // Find existing coverage comment
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const existingComment = comments.data.find(comment => 
              comment.body.includes('🧪 Test Coverage Summary') &&
              comment.body.includes('*Generated by CI Pipeline* 🤖') &&
              comment.body.includes('<!-- CI-COVERAGE-SUMMARY -->')
            );
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                comment_id: existingComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: coverageSummary
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: coverageSummary
              });
            }
          } catch (error) {
            console.log('Error posting coverage comment:', error.message);
            core.warning('Unable to post coverage comment due to permissions. Coverage results are available in the workflow logs.');
          }

  # Terraform Plan (on PR)
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./infra/terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        # Initialize with backend configuration
        # Backend details are set via environment variables
        terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=${GITHUB_REF_NAME}/terraform.tfstate" \
          -backend-config="region=${AWS_REGION}" \
          -backend-config="dynamodb_table=${TF_LOCK_TABLE}" \
          -backend-config="encrypt=true"
      env:
        TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
        TF_LOCK_TABLE: ${{ secrets.TF_LOCK_TABLE }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: |
        # Set stage based on branch name (trunk-based development)
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        
        if [[ "$BRANCH_NAME" == "main" ]]; then
          STAGE="prod"
        else
          # Clean branch name for ECR repository naming
          STAGE=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
        fi
        
        # Get AWS account ID for ECR repository URLs
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        terraform plan -no-color -input=false \
          -var="jwt_access_secret=${{ secrets.JWT_ACCESS_SECRET }}" \
          -var="jwt_refresh_secret=${{ secrets.JWT_REFRESH_SECRET }}" \
          -var="video_api_image=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/fiap-hackaton-$STAGE/video:latest" \
          -var="worker_image=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/fiap-hackaton-$STAGE/worker:latest"
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      continue-on-error: true
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Action: \`${{ github.event_name }}\`*
            
            <!-- CI-TERRAFORM-PLAN -->`;

            // Find existing Terraform comment
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const existingComment = comments.data.find(comment => 
              comment.body.includes('#### Terraform Format and Style') && 
              comment.body.includes('#### Terraform Plan') &&
              comment.body.includes('*Action: `${{ github.event_name }}`*') &&
              comment.body.includes('<!-- CI-TERRAFORM-PLAN -->')
            );
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                comment_id: existingComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            }
          } catch (error) {
            console.log('Error posting comment:', error.message);
            core.warning('Unable to post PR comment due to permissions. Plan results are available in the workflow logs.');
          }

    - name: Create Workflow Summary
      if: github.event_name == 'pull_request'
      run: |
        echo "### Terraform Plan Results 📋" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Format Check:** ${{ steps.fmt.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "**Initialization:** ${{ steps.init.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "**Validation:** ${{ steps.validate.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "**Plan:** ${{ steps.plan.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📝 Full plan details are available in the workflow logs above." >> $GITHUB_STEP_SUMMARY

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
