name: test

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:ci -w ${{ inputs.service-path }}
      - run: npm run typecheck:ci -w ${{ inputs.service-path }}
