name: User

on:
  push:
    branches: [main]
    paths:
      - apps/user/**
      - .github/workflows/user.yml
      - .github/workflows/test.reusable.yml
  pull_request:
    paths:
      - apps/user/**
      - .github/workflows/user.yml
      - .github/workflows/test.reusable.yml

jobs:
  tests:
    uses: ./.github/workflows/test.reusable.yml
    with:
      service-path: apps/user
    secrets: inherit