name: User

on:
  push:
    branches: [main]
  #     - main
  #   paths:
  #     - apps/user/**
  #     - .github/workflows/user.yml
  #     - .github/workflows/*.reusable.yml
  # pull_request:
  #   paths:
  #     - apps/user/**
  #     - .github/workflows/user.yml
  #     - .github/workflows/*.reusable.yml

jobs:
  tests:
    uses: ./.github/workflows/test.reusable.yml
    with:
      service-path: apps/user
    secrets: inherit
    if: ${{ !contains(fromJSON('["delete", "workflow_dispatch"]'), github.event_name) }}