name: User

on:
  push:
    branches: [main]
    paths:
      - apps/user/**
      - .github/workflows/user.yml
      - .github/workflows/test.reusable.yml
  pull_request:
    paths:
      - apps/user/**
      - .github/workflows/user.yml
      - .github/workflows/test.reusable.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://test:test@localhost:5432/test"
      JWT_ACCESS_SECRET: "test-access-secret"
      JWT_REFRESH_SECRET: "test-refresh-secret"
      JWT_ACCESS_EXPIRES_IN: "15m"
      JWT_REFRESH_EXPIRES_IN: "7d"
      PORT: 3000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate --schema=apps/user/prisma/schema.prisma
      - run: npm run lint -w apps/user
      - run: npm run typecheck -w apps/user

  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://test:test@localhost:5432/test"
      JWT_ACCESS_SECRET: "test-access-secret"
      JWT_REFRESH_SECRET: "test-refresh-secret"
      JWT_ACCESS_EXPIRES_IN: "15m"
      JWT_REFRESH_EXPIRES_IN: "7d"
      PORT: 3000
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate --schema=apps/user/prisma/schema.prisma
      - run: npx prisma migrate deploy --schema=apps/user/prisma/schema.prisma
      - run: npm run test -w apps/user
  # tests:
  #   uses: ./.github/workflows/test.reusable.yml
  #   with:
  #     service-path: apps/user
  #   secrets: inherit